version: 2.1
jobs:
  test:
    docker:
      - image: stefanprodan/kube-tools
    steps:
      - checkout
      - run:
          name: Test
          command: |
            kubectl version --client
            kustomize version
            helm version --client
            helmv3 version
            kubeval --version
            conftest --version
            yq --version
            jq --version
            go version

workflows:
  version: 2
  validate:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
