version: 2.1
jobs:
  build-test-push:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout

workflows:
  version: 2
  stable:
    jobs:
      - build-test-push:
          filters:
            branches:
              ignore:
                - v1