name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: conftest
        uses: ./
        with:
          command: |
            kustomize build test/kustomize | conftest test -p test/policy -
      - name: kubeval
        uses: ./
        with:
          command: |
            kustomize build test/kustomize | kubeval --strict --ignore-missing-schemas
